apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-dvtk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-dvtk
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-dvtk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-dvtk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-dvtk
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-ycbd-tenant/dotnet-component/devfile-sample-dotnet60-basic-dvtk@sha256:c40528943415d62823782f75d2770b59a16fd2c8d62182e8f8f975585bacda9e
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
